import type { Metadata } from "next";
import "./globals.css";
import Theme from "@/theme/Theme";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Theme>
                    {children}
                </Theme>
            </body>
        </html>
    );
}
