"use client"

// import type { Metadata } from "next";
import Theme from "@/theme/Theme";
import { AuthProvider } from "@il4mb/satupintu";

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Theme>
                    <AuthProvider appId="1" publicKey="" endpoint="">
                        {children}
                    </AuthProvider>
                </Theme>
            </body>
        </html>
    );
}
